
export const buttonValues=[
    {
        id:1,
        value:'C',
        bgcolor:"404040"
    },
    {
        id:2,
        value:'<=',
        //value:'../images/backspace.png',//back symbol
        bgcolor:"404040"
    },
    {
        id:3,
        value:'%',
        bgcolor:"404040"
    },
    {
        id:4,
        value:'/',
        bgcolor:"404040"
    },
    {
        id:5,
        value:'7',
        bgcolor:'0d0d0d'
    },
    {
        id:6,
        value:'8',
        bgcolor:'0d0d0d'
    },
    {
        id:7,
        value:'9',
        bgcolor:'0d0d0d'
    },
    {
        id:8,
        value:'*',
        bgcolor:"404040"
    },
    {
        id:9,
        value:'4',
        bgcolor:'0d0d0d'
    },
    {
        id:10,
        value:'5',
        bgcolor:'0d0d0d'
    },
    {
        id:11,
        value:'6',
        bgcolor:'0d0d0d'
    },
    {
        id:12,
        value:'-',
        bgcolor:"404040"
    },
    {
        id:13,
        value:'1',
        bgcolor:'0d0d0d'
    },
    {
        id:14,
        value:'2',
        bgcolor:'0d0d0d'
    },
    {
        id:15,
        value:'3',
        bgcolor:'0d0d0d'
    },
    {
        id:16,
        value:'+',
        bgcolor:"404040"
    },
    {
        id:17,
        value:'00',
        bgcolor:'0d0d0d'
    },
    {
        id:18,
        value:'0',
        bgcolor:'0d0d0d'
    },
    {
        id:19,
        value:'.',
        bgcolor:'0d0d0d'
    },
    {
        id:20,
        value:'=',
        bgcolor:'ff8c1a'
    }
]